### ISSUE TITLE
Wrong HTI for two atom system

### ISSUE THREAD

**Issue by chtchelkatchev** [deepmodeling/dpti#80]
Using the latest version of DPTI I tried to reproduce results that I had got by old version of DPTI two years ago (see https://doi.org/10.1063/5.0165948) for Bohr-Phosphorus system. Thermodynamic integration of solid B-P went correctly with the latest version of DPTI, however when I modified FreeEnergy.json for liquid calculation, things went wrong. At HTI stage DPTI missed that the system consists of two sorts of atoms, e.g.:
pair_coeff      1 1 ${EPSILON} 1.300000 0.500000
pair_coeff      1 2  --- missing
pair_coeff      2 2  --- missing
Of cause I inserted the mass map with two masses and three sigma in a proper way, like it was done two years ago. INPUT files for DPTI I attach. There is a typo somewhere in DPTI-soft-code that triggers the mistake. Please, take a look.

[DPTI_input.zip](https://github.com/user-attachments/files/17646708/DPTI_input.zip)

**Comment by Yi-FanLi** [comment]
I am going to take a look soon.

**Comment by Yi-FanLi** [comment]
Hi @chtchelkatchev, I reproduced your issue. Thanks for providing us with your input files! I fixed this issue in https://github.com/deepmodeling/dpti/pull/81.
